"""add paynow poll url and reference fields

Revision ID: 068af20d4b64
Revises: b2c3d4e5f6a7
Create Date: 2026-07-18 14:14:08.739632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '068af20d4b64'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_rate_limit_buckets_client_ip'), 'rate_limit_buckets', type_='unique')
    op.drop_constraint(op.f('uq_revoked_tokens_jti'), 'revoked_tokens', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_revoked_tokens_jti'), 'revoked_tokens', ['jti'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_rate_limit_buckets_client_ip'), 'rate_limit_buckets', ['client_ip'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
