"""initial_clean_schema

Revision ID: 181cca4e29d6
Revises: 
Create Date: 2026-08-05 09:57:10.449049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '181cca4e29d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revoked_tokens_jti'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_index(op.f('ix_rate_limit_buckets_client_ip'), table_name='rate_limit_buckets')
    op.drop_table('rate_limit_buckets')
    op.alter_column('activities', 'time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.alter_column('events', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('events', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('events', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('events', 'registration_opens',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('events', 'registration_closes',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('events', 'voting_opens',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('events', 'voting_closes',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('events', 'public_leaderboard',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('events', 'require_contestant_approval',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_events_competition_id'), table_name='events')
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_end_date'), 'events', ['end_date'], unique=False)
    op.create_index(op.f('ix_events_name'), 'events', ['name'], unique=False)
    op.create_index(op.f('ix_events_start_date'), 'events', ['start_date'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.drop_column('events', 'allowed_categories')
    op.drop_column('events', 'allowed_platforms')
    op.drop_column('events', 'competition_id')

    contestant_status_enum = postgresql.ENUM('approved', 'disqualified', name='contestantstatus')    
    contestant_status_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column('participants', 'status',
               existing_type=postgresql.ENUM('approved', 'disqualified', name='contestant_status'),
               type_=sa.Enum('approved', 'disqualified', name='contestantstatus'),
              existing_nullable=False,
               postgresql_using='status::text::contestantstatus')
    op.alter_column('participants', 'votes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('participants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('participants', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('participants', 'event_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_participants_category'), 'participants', ['category'], unique=False)
    op.create_index(op.f('ix_participants_created_at'), 'participants', ['created_at'], unique=False)
    op.create_index(op.f('ix_participants_event_id'), 'participants', ['event_id'], unique=False)
    op.create_index(op.f('ix_participants_name'), 'participants', ['name'], unique=False)
    op.create_index(op.f('ix_participants_status'), 'participants', ['status'], unique=False)
    op.create_index(op.f('ix_participants_votes'), 'participants', ['votes'], unique=False)
    op.alter_column('payment_method_configs', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('payment_method_configs', 'config_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_payment_method_configs_enabled'), table_name='payment_method_configs')
    op.drop_index(op.f('ix_payment_method_configs_sort'), table_name='payment_method_configs')
    op.alter_column('payments', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('settings', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('settings', 'support_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('settings', 'timezone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('settings', 'email_notifications',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('settings', 'sms_notifications',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('settings', 'marketing_notifications',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('test_payments', sa.Column('event_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('test_payments_reference_key'), 'test_payments', type_='unique')
    op.drop_index(op.f('ix_test_payments_reference'), table_name='test_payments')
    op.create_index(op.f('ix_test_payments_reference'), 'test_payments', ['reference'], unique=True)
    op.drop_column('test_payments', 'competition_id')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'reset_token_expires',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'invitation_token_expires',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'locked_until',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint(op.f('users_refresh_token_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_refresh_token'), table_name='users')
    op.create_index(op.f('ix_users_refresh_token'), 'users', ['refresh_token'], unique=True)
    op.add_column('vote_transactions', sa.Column('event_id', sa.String(), nullable=True))
    op.alter_column('vote_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_vote_transactions_competition_id'), table_name='vote_transactions')
    op.create_index(op.f('ix_vote_transactions_event_id'), 'vote_transactions', ['event_id'], unique=False)
    op.create_foreign_key(None, 'vote_transactions', 'events', ['event_id'], ['id'])
    op.drop_column('vote_transactions', 'competition_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote_transactions', sa.Column('competition_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vote_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_vote_transactions_event_id'), table_name='vote_transactions')
    op.create_index(op.f('ix_vote_transactions_competition_id'), 'vote_transactions', ['competition_id'], unique=False)
    op.alter_column('vote_transactions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('vote_transactions', 'event_id')
    op.drop_index(op.f('ix_users_refresh_token'), table_name='users')
    op.create_index(op.f('ix_users_refresh_token'), 'users', ['refresh_token'], unique=False)
    op.create_unique_constraint(op.f('users_refresh_token_key'), 'users', ['refresh_token'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'locked_until',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'invitation_token_expires',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'reset_token_expires',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('test_payments', sa.Column('competition_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_test_payments_reference'), table_name='test_payments')
    op.create_index(op.f('ix_test_payments_reference'), 'test_payments', ['reference'], unique=False)
    op.create_unique_constraint(op.f('test_payments_reference_key'), 'test_payments', ['reference'], postgresql_nulls_not_distinct=False)
    op.drop_column('test_payments', 'event_id')
    op.alter_column('settings', 'marketing_notifications',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('settings', 'sms_notifications',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('settings', 'email_notifications',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('settings', 'timezone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('settings', 'support_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('settings', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('payments', 'date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_payment_method_configs_sort'), 'payment_method_configs', ['sort_order'], unique=False)
    op.create_index(op.f('ix_payment_method_configs_enabled'), 'payment_method_configs', ['is_enabled'], unique=False)
    op.alter_column('payment_method_configs', 'config_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('payment_method_configs', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_participants_votes'), table_name='participants')
    op.drop_index(op.f('ix_participants_status'), table_name='participants')
    op.drop_index(op.f('ix_participants_name'), table_name='participants')
    op.drop_index(op.f('ix_participants_event_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_created_at'), table_name='participants')
    op.drop_index(op.f('ix_participants_category'), table_name='participants')
    op.alter_column('participants', 'event_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('participants', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('participants', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('participants', 'votes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('participants', 'status',
               existing_type=sa.Enum('approved', 'disqualified', name='contestantstatus'),
               type_=postgresql.ENUM('approved', 'disqualified', name='contestant_status'),
               existing_nullable=False)
    op.add_column('events', sa.Column('competition_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('allowed_platforms', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('allowed_categories', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_start_date'), table_name='events')
    op.drop_index(op.f('ix_events_name'), table_name='events')
    op.drop_index(op.f('ix_events_end_date'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.create_index(op.f('ix_events_competition_id'), 'events', ['competition_id'], unique=False)
    op.alter_column('events', 'require_contestant_approval',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('events', 'public_leaderboard',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('events', 'voting_closes',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('events', 'voting_opens',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('events', 'registration_closes',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('events', 'registration_opens',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('events', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('events', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('events', 'end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('events', 'start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.alter_column('audit_logs', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('activities', 'time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_table('rate_limit_buckets',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('client_ip', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('window_start', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('request_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('rate_limit_buckets_pkey'))
    )
    op.create_index(op.f('ix_rate_limit_buckets_client_ip'), 'rate_limit_buckets', ['client_ip'], unique=True)
    op.create_table('revoked_tokens',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('jti', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('revoked_tokens_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('revoked_tokens_pkey'))
    )
    op.create_index(op.f('ix_revoked_tokens_jti'), 'revoked_tokens', ['jti'], unique=True)
    # ### end Alembic commands ###
