"""add user token columns

Revision ID: ad71a2c892e3
Revises: d3e5a257eff5
Create Date: 2026-07-18 00:08:02.823653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad71a2c892e3'
down_revision: Union[str, Sequence[str], None] = 'd3e5a257eff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('invitation_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('invitation_token_expires', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('invited_by', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_invitation_token'), 'users', ['invitation_token'], unique=True)
    op.create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    op.drop_index(op.f('ix_users_invitation_token'), table_name='users')
    op.drop_column('users', 'invited_by')
    op.drop_column('users', 'invitation_token_expires')
    op.drop_column('users', 'invitation_token')
    op.drop_column('users', 'reset_token_expires')
    op.drop_column('users', 'reset_token')
    # ### end Alembic commands ###
