"""add minimum_payment to events

Revision ID: e5253de3ce14
Revises: 181cca4e29d6
Create Date: 2026-08-06 20:14:04.857375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5253de3ce14'
down_revision: Union[str, Sequence[str], None] = '181cca4e29d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('minimum_payment', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'minimum_payment')
    # ### end Alembic commands ###
