import type {
  EventRecord,
  ParticipantRecord,
  PaymentRecord,
  ActivityRecord,
  DashboardSummary,
  SettingsProfile,
  PaymentMethodOption,
  SocialPlatformStatus,
} from "./types"

export const paymentMethods: PaymentMethodOption[] = [
  { id: "ecocash", name: "EcoCash", type: "mobile_money", isPrimary: true },
  { id: "onemoney", name: "OneMoney", type: "mobile_money" },
  { id: "innbucks", name: "InnBucks", type: "mobile_money" },
  { id: "omari", name: "Omari", type: "mobile_money" },
  { id: "zimswitch", name: "Zimswitch", type: "card" },
  { id: "visa", name: "Visa", type: "card" },
  { id: "mastercard", name: "Mastercard", type: "card" },
  { id: "paypal", name: "PayPal", type: "digital_wallet" },
  { id: "applepay", name: "Apple Pay", type: "digital_wallet" },
  { id: "googlepay", name: "Google Pay", type: "digital_wallet" },
]

export const events: EventRecord[] = [
  {
    id: "evt-001",
    name: "Summer Spotlight 2026",
    description:
      "Our flagship creative showdown returns for its biggest season yet. Watch the most talented performers across Southern Africa compete for the crown — and your vote decides who takes it home.",
    banner: null,
    startDate: "2026-07-01T00:00:00Z",
    endDate: "2026-07-28T23:59:59Z",
    status: "Voting Open",
    votePrice: 1.0,
    votesPerPayment: -1,
    currency: "USD",
    votingOpens: "2026-07-10T08:00:00Z",
    votingCloses: "2026-07-28T22:00:00Z",
    publicLeaderboard: true,
    allowedCategories: "Singing,Dancing,Comedy,Acting,Fashion",
    allowedPlatforms: "TikTok,Facebook,Instagram,YouTube",
  },
  {
    id: "evt-002",
    name: "Campus Crown",
    description:
      "Regional campus contest with platform-driven voting and weekly eliminations.",
    banner: null,
    startDate: "2026-08-04T00:00:00Z",
    endDate: "2026-08-24T23:59:59Z",
    status: "Upcoming",
    votePrice: 0.5,
    votesPerPayment: -1,
    currency: "USD",
    votingOpens: "2026-08-10T08:00:00Z",
    votingCloses: "2026-08-24T22:00:00Z",
    publicLeaderboard: true,
    allowedCategories: "Singing,Dancing,Comedy",
    allowedPlatforms: "TikTok,Facebook,Instagram,YouTube",
  },
  {
    id: "evt-003",
    name: "Night Stage Finals",
    description:
      "Archived finale event with completed vote processing and payouts.",
    banner: null,
    startDate: "2026-05-12T00:00:00Z",
    endDate: "2026-06-02T23:59:59Z",
    status: "Completed",
    votePrice: 2.0,
    votesPerPayment: -1,
    currency: "USD",
    votingOpens: null,
    votingCloses: null,
    publicLeaderboard: false,
    allowedCategories: "Singing,Dancing",
    allowedPlatforms: "TikTok,YouTube",
  },
]

export const participants: ParticipantRecord[] = [
  {
    id: "part-001",
    name: "Mira Patel",
    category: "Dancing",
    platform: "TikTok",
    videoUrl: "https://www.tiktok.com/@mira/video/1",
    status: "Approved",
    votes: 12840,
    bio: "Choreographer and dancer from Harare. 8 years of contemporary and afro-fusion dance experience. Three-time regional finalist.",
    imageUrl: null,
    eventId: "evt-001",
  },
  {
    id: "part-002",
    name: "Jordan Lewis",
    category: "Singing",
    platform: "Instagram",
    videoUrl: "https://instagram.com/reel/abc123",
    status: "Approved",
    votes: 9875,
    bio: "Soul and R&B vocalist from Bulawayo. Known for powerful vocal range and emotive performances.",
    imageUrl: null,
    eventId: "evt-001",
  },
  {
    id: "part-003",
    name: "Anika Sharma",
    category: "Comedy",
    platform: "YouTube",
    videoUrl: "https://youtube.com/watch?v=demo",
    status: "Approved",
    votes: 6120,
    bio: "Stand-up comedian and content creator. Specializes in observational humor about everyday Zimbabwean life.",
    imageUrl: null,
    eventId: "evt-001",
  },
  {
    id: "part-004",
    name: "Chris Barnes",
    category: "Acting",
    platform: "Facebook",
    videoUrl: "https://facebook.com/watch/demo",
    status: "Approved",
    votes: 4530,
    bio: "Theatre actor with a growing social media presence. Known for dramatic monologues and short film performances.",
    imageUrl: null,
    eventId: "evt-001",
  },
  {
    id: "part-005",
    name: "Tariro Ndlovu",
    category: "Singing",
    platform: "TikTok",
    videoUrl: "https://www.tiktok.com/@tariro/video/2",
    status: "Approved",
    votes: 8340,
    bio: "Afro-pop singer-songwriter from Mutare. Blends traditional Shona melodies with modern production.",
    imageUrl: null,
    eventId: "evt-001",
  },
  {
    id: "part-006",
    name: "Lisa Chen",
    category: "Dancing",
    platform: "Instagram",
    videoUrl: "https://instagram.com/reel/xyz789",
    status: "Approved",
    votes: 7210,
    bio: "Hip-hop and street dance specialist. Part of the Zim Street Collective crew based in Harare.",
    imageUrl: null,
    eventId: "evt-001",
  },
  {
    id: "part-007",
    name: "David Moyo",
    category: "Comedy",
    platform: "YouTube",
    videoUrl: "https://youtube.com/watch?v=demo2",
    status: "Under Review",
    votes: 0,
    bio: "Sketch comedy creator. Popular for his relatable skits about family life and school days.",
    imageUrl: null,
    eventId: "evt-001",
  },
  {
    id: "part-008",
    name: "Fatima Ali",
    category: "Fashion",
    platform: "TikTok",
    videoUrl: "https://www.tiktok.com/@fatima/video/3",
    status: "Approved",
    votes: 3920,
    bio: "Fashion designer and stylist showcasing original designs inspired by African textiles and modern streetwear.",
    imageUrl: null,
    eventId: "evt-001",
  },
  {
    id: "part-009",
    name: "Sean Williams",
    category: "Acting",
    platform: "Facebook",
    videoUrl: "https://facebook.com/watch/demo2",
    status: "Approved",
    votes: 5180,
    bio: "Method actor and voice-over artist. Performs dramatic interpretations of trending topics.",
    imageUrl: null,
    eventId: "evt-001",
  },
  {
    id: "part-010",
    name: "Nomsa Dube",
    category: "Singing",
    platform: "YouTube",
    videoUrl: "https://youtube.com/watch?v=demo3",
    status: "Approved",
    votes: 6780,
    bio: "Gospel and traditional vocalist. Her acapella performances have earned her a loyal following across platforms.",
    imageUrl: null,
    eventId: "evt-001",
  },
  {
    id: "part-011",
    name: "Kuda Mabhena",
    category: "Dancing",
    platform: "TikTok",
    videoUrl: "https://www.tiktok.com/@kuda/video/4",
    status: "Approved",
    votes: 5890,
    bio: "Breakdancer and contemporary dance artist from Gweru. Competed internationally at Afro Dance Battles.",
    imageUrl: null,
    eventId: "evt-001",
  },
  {
    id: "part-012",
    name: "Precious Ncube",
    category: "Comedy",
    platform: "Instagram",
    videoUrl: "https://instagram.com/reel/comedy1",
    status: "Approved",
    votes: 3150,
    bio: "Improv comedian and host. Known for quick wit and crowd work during live performances.",
    imageUrl: null,
    eventId: "evt-001",
  },
]

export const payments: PaymentRecord[] = [
  {
    id: "pay-001",
    reference: "VOTE-2026-1048",
    contestantId: "part-001",
    contestantName: "Mira Patel",
    amount: 1.0,
    paymentMethod: "EcoCash",
    status: "Paid",
    date: "2026-07-15T09:18:00Z",
  },
  {
    id: "pay-002",
    reference: "VOTE-2026-1059",
    contestantId: "part-002",
    contestantName: "Jordan Lewis",
    amount: 1.0,
    paymentMethod: "OneMoney",
    status: "Pending",
    date: "2026-07-15T11:02:00Z",
  },
  {
    id: "pay-003",
    reference: "VOTE-2026-1061",
    contestantId: "part-003",
    contestantName: "Anika Sharma",
    amount: 1.0,
    paymentMethod: "Visa",
    status: "Failed",
    date: "2026-07-14T18:30:00Z",
  },
  {
    id: "pay-004",
    reference: "VOTE-2026-1072",
    contestantId: "part-005",
    contestantName: "Tariro Ndlovu",
    amount: 1.0,
    paymentMethod: "EcoCash",
    status: "Paid",
    date: "2026-07-16T08:45:00Z",
  },
  {
    id: "pay-005",
    reference: "VOTE-2026-1083",
    contestantId: "part-001",
    contestantName: "Mira Patel",
    amount: 1.0,
    paymentMethod: "PayPal",
    status: "Paid",
    date: "2026-07-16T10:22:00Z",
  },
  {
    id: "pay-006",
    reference: "VOTE-2026-1094",
    contestantId: "part-006",
    contestantName: "Lisa Chen",
    amount: 1.0,
    paymentMethod: "InnBucks",
    status: "Processing",
    date: "2026-07-16T14:05:00Z",
  },
  {
    id: "pay-007",
    reference: "VOTE-2026-1105",
    contestantId: "part-009",
    contestantName: "Sean Williams",
    amount: 1.0,
    paymentMethod: "Mastercard",
    status: "Paid",
    date: "2026-07-17T07:30:00Z",
  },
]

export const activities: ActivityRecord[] = [
  {
    id: "act-001",
    title: "Votes synchronized",
    detail: "Processed 1,250 votes across active contestants.",
    time: "2026-07-17T09:30:00Z",
  },
  {
    id: "act-002",
    title: "Payment captured",
    detail: "EcoCash payment of $1.00 for Mira Patel confirmed.",
    time: "2026-07-17T09:15:00Z",
  },
  {
    id: "act-003",
    title: "New contestant approved",
    detail: "Precious Ncube cleared for voting in Summer Spotlight.",
    time: "2026-07-17T08:45:00Z",
  },
  {
    id: "act-004",
    title: "Event published",
    detail: "Campus Crown moved to upcoming schedule.",
    time: "2026-07-16T16:00:00Z",
  },
  {
    id: "act-005",
    title: "Payment failed",
    detail: "Visa transaction for Anika Sharma was declined.",
    time: "2026-07-16T14:20:00Z",
  },
]

export const dashboardSummary: DashboardSummary = {
  activeEvent: "Summer Spotlight 2026",
  totalParticipants: 11,
  totalVotes: 73835,
  totalRevenue: "$3,240.00",
  recentPayments: payments.slice(0, 5),
  recentActivity: activities.slice(0, 5),
}

export const settings: SettingsProfile = {
  companyName: "VibeWave",
  supportEmail: "support@vibewave.co.zw",
  timezone: "Africa/Harare",
  notifications: {
    email: true,
    sms: false,
    marketing: false,
  },
}

export const socialPlatforms: SocialPlatformStatus[] = [
  {
    id: "soc-001",
    platform: "TikTok",
    status: "Connected",
    lastSync: "2 minutes ago",
    detail: "Real-time vote sync is active. Video metadata pulling is healthy.",
  },
  {
    id: "soc-002",
    platform: "Facebook",
    status: "Syncing",
    lastSync: "Now",
    detail: "Queued metadata updates are being processed for 3 contestants.",
  },
  {
    id: "soc-003",
    platform: "Instagram",
    status: "Failed",
    lastSync: "26 minutes ago",
    detail: "API rate limit reached. Will retry automatically in 5 minutes.",
  },
  {
    id: "soc-004",
    platform: "YouTube",
    status: "Disconnected",
    lastSync: "3 hours ago",
    detail: "OAuth token expired. Reconnection required to resume video metadata sync.",
  },
]

export const adminUsers = [
  { id: "usr-001", name: "Tendai Moyo", email: "tendai@vibewave.co.zw", role: "Super Admin" as const, isActive: true, createdAt: "2026-01-15T10:00:00Z" },
  { id: "usr-002", name: "Sarah Johnson", email: "sarah@vibewave.co.zw", role: "Admin" as const, isActive: true, createdAt: "2026-03-22T14:30:00Z" },
  { id: "usr-003", name: "Mike Dube", email: "mike@vibewave.co.zw", role: "Admin" as const, isActive: true, createdAt: "2026-05-10T09:00:00Z" },
  { id: "usr-004", name: "Grace Ncube", email: "grace@vibewave.co.zw", role: "Moderator" as const, isActive: false, createdAt: "2026-06-01T11:15:00Z" },
]